# Generated by Django 4.2.2 on 2023-09-06 09:02

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAndConvenience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='car-review/safety_convenience')),
                ('rated_by_orient_motors', models.PositiveSmallIntegerField(default=0)),
                ('car_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_convenience', to='review.carreview')),
            ],
            options={
                'db_table': 'review_safety_and_convenience',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SafetyAndConvenienceAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_convenience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='review.safetyandconvenience')),
            ],
            options={
                'db_table': 'review_safety_convenience_advantage',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SafetyAndConvenienceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('safety_equipment', models.TextField()),
                ('convenience_equipment', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='review.safetyandconvenience')),
            ],
            options={
                'verbose_name': 'safety and convenience Translation',
                'db_table': 'review_safety_and_convenience_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SafetyAndConvenienceAdvantagesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='review.safetyandconvenienceadvantages')),
            ],
            options={
                'verbose_name': 'safety and convenience advantages Translation',
                'db_table': 'review_safety_convenience_advantage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
