# Generated by Django 4.2.2 on 2023-09-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_sizeandspace_rated_by_orient_motors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceandmanagementtranslation',
            old_name='Service',
            new_name='service',
        ),
    ]
