# Generated by Django 4.2.2 on 2023-09-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_rename_service_maintenanceandmanagementtranslation_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizeandspace',
            old_name='length',
            new_name='length_photo',
        ),
    ]
