# Generated by Django 4.2.2 on 2023-08-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticsfaqtranslation',
            old_name='qestion',
            new_name='question',
        ),
    ]
