# Generated by Django 4.2.2 on 2023-08-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_qestion_diagnosticsfaqtranslation_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumdiagnosticsfaqtranslation',
            old_name='qestion',
            new_name='question',
        ),
    ]
