# Generated by Django 4.2.2 on 2023-08-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_qestion_premiumdiagnosticsfaqtranslation_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticspecialiststranslation',
            name='specialty',
            field=models.CharField(max_length=200),
        ),
    ]
