# Generated by Django 4.2.2 on 2023-06-19 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodytype',
            name='used',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='used',
        ),
        migrations.RemoveField(
            model_name='service',
            name='used',
        ),
        migrations.RemoveField(
            model_name='transmission',
            name='used',
        ),
        migrations.AddField(
            model_name='brand',
            name='used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.color'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.fuel'),
        ),
        migrations.AddField(
            model_name='car',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.transmission'),
        ),
        migrations.AddField(
            model_name='model',
            name='used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
