# Generated by Django 4.2.2 on 2023-06-22 06:19

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_bodytype_used_remove_fuel_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colortranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cars.color'),
        ),
    ]
