# Generated by Django 4.2.2 on 2023-08-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carphotos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='rate',
            new_name='rated',
        ),
    ]
