# Generated by Django 4.2.2 on 2023-06-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_colortranslation_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='currency',
            field=models.CharField(choices=[('Usd', 'usd'), ('Uzs', 'uzs')], default='uzs', max_length=4),
            preserve_default=False,
        ),
    ]
