# Generated by Django 4.2.2 on 2023-06-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_owned_by_orient_motors_car_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ishlab chiqarilgan oy', null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Ishlab chiqarilgan yil'),
        ),
    ]
