# Generated by Django 4.2.2 on 2023-09-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0002_driveunit_paintcondition_paintconditiontranslation_and_more'),
        ('cars', '0006_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='drive_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='specifications.driveunit'),
        ),
        migrations.AddField(
            model_name='car',
            name='paint_condition',
            field=models.ManyToManyField(related_name='cars', to='specifications.paintcondition'),
        ),
    ]
