# Generated by Django 4.2.2 on 2023-09-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_drive_unit_car_paint_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='number_of_owners',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
