# Generated by Django 4.2.2 on 2023-10-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0003_externalbodykit_mediatools_optics_salon_and_more'),
        ('cars', '0009_car_media_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='external_body_kit',
            field=models.ManyToManyField(related_name='cars', to='specifications.externalbodykit'),
        ),
        migrations.AddField(
            model_name='car',
            name='optics',
            field=models.ManyToManyField(related_name='cars', to='specifications.optics'),
        ),
        migrations.AddField(
            model_name='car',
            name='salon',
            field=models.ManyToManyField(related_name='cars', to='specifications.salon'),
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_options',
            field=models.ManyToManyField(related_name='cars', to='specifications.vehicleoptions'),
        ),
    ]
