# Generated by Django 4.2.2 on 2023-08-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_branch_branchesphoto_branchtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchesphoto',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.branch'),
        ),
    ]
