# Generated by Django 4.2.2 on 2023-08-11 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_branchesphoto_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintToBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_to_branches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
